### ISSUE TITLE
Support for localization

### ISSUE THREAD

**Issue by kobe25** [befair/gasistafelice#179]
Support for the translation of the (new) UI in more languages.

**Comment by feroda** [comment]
At a first glance, i18n and l10n in the AngularJS world is a big mess. There are differents solutions to achieve the goal and [the official guide to i18n](https://docs.angularjs.org/guide/i18n) is outdated and does not provide a way to store strings translations, nor a standard format. WHAT THE Fxxx ANGULAR IS?!? Is it really ready for production?

I think we should choose the simplest way for us to achieve a goal with only the feature we need:

* we need to support multiple languages: translate strings with parameters and pluralization; in order to do this we need some sort of **directive** to mark strings to be translated in templates.
* we do not really need to adapt the language/locale setting during website visit (a window reload is tolerated);
* we do not need to support different currencies in l10n, because they can be different among products. So they should be given by the backend rather than appended by the frontend;
* we do not need too much CamelCase in our code ;)
* we really like an autogenerator for files to be localized (like the makemessages for django.po in the backend)

SOLUTIONS CAN BE, in order of "sex appeal" to me:

* https://github.com/doshprompt/angular-localization <--- AngularJS localization done right :+1: 
* https://github.com/blueimp/angular-localize
* http://codingsmackdown.tv/blog/2012/12/14/localizing-your-angularjs-app/

TO READ:
* https://alicoding.com/how-to-localized-angularjs-app/
* http://codingsmackdown.tv/blog/2012/12/14/localizing-your-angularjs-app/

Any comments?

**Comment by feroda** [comment]
I have tried angular-localization and I think it can work now for us. I don't know if it is the best choice, but in this situation I think it can do, and I really prefer that everyone in the team can play asap with i18n and l10n in order to experiment its hassles

**Comment by kobe25** [comment]
Have you seen [angular translate](https://angular-translate.github.io/)?  It seems the most popular library right now.

**Comment by feroda** [comment]
Thanks, now I have seen it ;)

I think the best choice for us is [angular-gettext](https://angular-gettext.rocketeer.be/) because it is based on .pot and .po files that are standard and so many tools can be used to manage them. I care that users can provide i18n by themselves.

**Comment by kobe25** [comment]
:+1:
